name: Starlink Docker Build and Push

on:
  push:
    branches: [ develop ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./src/
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/starlink_app:latest

      - name: Build and push nginx image
        uses: docker/build-push-action@v4
        with:
          context: ./nginx/
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/starlink_nginx:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "docker-compose.production.yml"
          target: "/opt/starlink/"

      - name: Generate .env on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE}}
          script: |
            mkdir -p /opt/starlink/
            cd /opt/starlink/
            rm .env
            touch .env
            echo "BOT_TOKEN=%s\n" "${{ secrets.BOT_TOKEN }}" >> .env
            echo "APP_TITLE='%s'\n" "Административная панель Starlink бот" >> .env
            echo "APP_DESCRIPTION='%s'\n" "Управление справочным чат ботом для сотрудников" >> .env
            echo "APP_VERSION='%s'\n" "1.0.0" >> .env
            echo "POSTGRES_USER=%s\n" "user" >> .env
            echo "POSTGRES_PASSWORD=%s\n" "${{ secrets.POSTGRES_PASSWORD }}" >> .env
            echo "POSTGRES_HOST=%s\n" "127.0.0.1" >> .env
            echo "POSTGRES_PORT=%s\n" "5432" >> .env
            echo "POSTGRES_DB=%s\n" "${{ secrets.POSTGRES_DB }}" >> .env
            echo "POSTGRES_DB_NAME=%s\n" "yourdbname" >> .env
            echo "SECRET_KEY=%s\n" "${{ secrets.SECRET_KEY }}" >> .env
            echo "ALGORITHM=%s\n" "HS256" >> .env
            echo "ACCESS_TOKEN_EXPIRE_MINUTES=%s\n" "30" >> .env
            echo "NOT_AUTHENTICATED='%s'\n" "Not authenticated" >> .env
            echo "ADMIN1_EMAIL=%s\n" "user1@gmail.com" >> .env
            echo "ADMIN1_PASSWORD=%s\n" "${{ secrets.ADMIN1_PASSWORD }}" >> .env
            echo "ADMIN2_EMAIL=%s\n" "user2@gmail.com" >> .env
            echo "ADMIN2_PASSWORD=%s\n" "${{ secrets.ADMIN2_PASSWORD }}" >> .env
            chmod 600 .env

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE}}
          script: |
            cd /opt/starlink/
            docker compose -f docker-compose.production.yml down
            docker compose -f docker-compose.production.yml pull
            docker compose -f docker-compose.production.yml up -d
